# Generated by Django 5.0 on 2025-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(default='', max_length=50, verbose_name='First Name')),
                ('ln', models.CharField(default='', max_length=50, verbose_name='Last Name')),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('msg', models.TextField(default='', verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'User Queries',
            },
        ),
    ]
