# Generated by Django 5.0 on 2025-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteInfo', '0002_contact_ss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ss',
            field=models.ImageField(default='', upload_to='ContactSS', verbose_name='Screenshot'),
        ),
    ]
