# Generated by Django 5.0 on 2025-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='BooksImgs'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
