# Generated by Django 5.0 on 2025-07-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_author_product_img_product_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
