# Generated by Django 5.0 on 2025-07-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_is_avil_product_is_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('E-Book', 'E-Book'), ('Paper', 'Paper')], default='E-Book', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='lang',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
