# Generated by Django 5.0 on 2025-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_product_file_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
