# Generated by Django 5.0 on 2025-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('Online', 'Online')], max_length=50, null=True),
        ),
    ]
