# Generated by Django 5.0 on 2025-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='direct_buy',
            field=models.BooleanField(default=False),
        ),
    ]
