# Generated by Django 5.0 on 2025-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(default=''),
        ),
    ]
