# Generated by Django 5.0 on 2025-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_product_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_avil',
            field=models.BooleanField(default=True),
        ),
    ]
