# Generated by Django 5.0 on 2025-07-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_product_is_avil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avil',
            new_name='is_avail',
        ),
    ]
