# Generated by Django 5.0 on 2025-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_payment_id',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
