# Generated by Django 5.0 on 2025-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
