# Generated by Django 5.0 on 2025-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ss',
            field=models.ImageField(default='', upload_to='ContactSS'),
        ),
    ]
